### ISSUE TITLE
Support for more data types

### ISSUE THREAD

**Issue by athre0z** [JuliaDatabases/ClickHouse.jl#11]
Many of the more advanced ClickHouse data-types are currently not supported in this client and it'd be great to support more of them. This issue tracks all ClickHouse types and their support status in this lib.

## Primitive types

- [x] `String`
- [x] `Float{32,64}`
- [x] `Int{8,16,32,64}`
- [x] `UInt{8,16,32,64}`
- [x] `Enum{8,16}`
- [x] `Date`, `DateTime`
- [x] `DateTime64`
- [x] `Decimal{32,64}`
- [x] `FixedString`
- [x] `UUID`
- [x] `IPv4` / `IPv6`

## Compound types

- [x] `Array(T)`
- [x] `Nullable(T)`
- [x] `LowCardinality(T)`
- [x] `Tuple`
- [x] `Nested`
  - These simplify to a sequence of array fields with dot separators in their name and essentially come free when implementing `Array(T)` support
- [x] `SimpleAggregateFunction`
- [x] `Nothing`
  - Not sure how useful this type is, but the Python client supports it ¯\_(ツ)_/¯

## General things that need figuring out

- [ ] ~~Some compound types can be nested, e.g. `LowCardinality(Nullable(String))` and `Array(Nullable(UInt8))` are valid, but `Nullable(Array(UInt8))` isn't. We should figure out these nesting rules.~~
- [x] We should implement a parser that can deal with parsing the string representation of arbitrarily nested types.
  - In the CH network protocol, the type of a block is transferred in the string representation that you'll also be presented with when executing `DESC my_table\G` in the terminal client

## References

Because the CH TCP protocol isn't documented, we have to resort to looking at the source of either the official C++ client or client implementations in other languages. The Python client has great coverage for all important types and is generally quite easy to navigate, so I particularly recommend this one for use as reference:
https://github.com/mymarilyn/clickhouse-driver/tree/master/clickhouse_driver/columns

## Contributing

If you are interested in helping out with adding support for one or more currently unsupported types, please feel free to claim the respective item(s) to avoid duplicated work or ask any organizational or technical questions by posting in this issue. You can also create a new issue with the particular type(s) that you'd like to work on and I'll just update this issue.

**Comment by waralex** [comment]
>We should figure out these nesting rules

This can be done, but the question is whether it is necessary? These types come from the server, the client user only edits them in `create table`, and we do not validate the content of `create table`. Don't you think it's unnecessary to duplicate server validation from the client side?

**Comment by athre0z** [comment]
Yeah, good point, will probably not be necessary and also quite a lot of unnecessary effort.  I'll strike the point.

**Comment by waralex** [comment]
If you are satisfied with the architecture presented in #10, then you can leave this issue entirely to me

**Comment by athre0z** [comment]
Absolutely! I'd however prefer if we could first land the PR with the types that it currently implements and then create a second one for the additional types instead of now adding additional types to the existing PR, because it's a lot easier to review the changes this way.

**Comment by waralex** [comment]
> instead of now adding additional types to the existing PR

Yes, of course. In #10, I added simple ones (and actually implemented already in my client prototype) more in order to demonstrate how the new architecture handles non-primitive types.
I would like to merge this PR as soon as possible and add the remaining types in another PRs

**Comment by athre0z** [comment]
Since 

```sql
CREATE TABLE oofsdf
(
    `x` Nested(    a Int32,     b Float32)
)
ENGINE = Memory
```

is just syntax sugar for

```
DESCRIBE TABLE oofsdf

┌─name─┬─type───────────┬─default_type─┬─default_expression─┬─comment─┬─codec_expression─┬─ttl_expression─┐
│ x.a  │ Array(Int32)   │              │                    │         │                  │                │
│ x.b  │ Array(Float32) │              │                    │         │                  │                │
└──────┴────────────────┴──────────────┴────────────────────┴─────────┴──────────────────┴────────────────┘
```

I also tagged this as complete and I think we can now close this issue!
