### ISSUE TITLE
Is this client currently developing? And can I find out your nearest plans?

### ISSUE THREAD

**Issue by waralex** [JuliaDatabases/ClickHouse.jl#6]
Hi!
I would like to know if this package is currently being actively developed. I really need a full-fledged client for ClickHouse and I am ready to join the development, but I would like to understand what You are doing now, so that it does not turn out that we do the same work.

My draft of working (partially) client is here https://github.com/waralex/ClickHouseDB. I started writing it in February. However, in the process of writing it, I got carried away with the idea of "trying if I can write something similar to clickhouse on Julia". As a result, I became interested in writing https://github.com/waralex/DataFrameDBs.jl 
And in April, I was approached by the guys from Plotly with an offer to turn my Dashboards.jl in the official plotly/Dash.jl and my free time is over :( But now I'm at my main job finished migrating from my self-written column database to clickhouse and the need for a client has become very acute. In addition, the main volume of Dash is done, it is moving towards release, and I finally have time again on the weekend for other projects.

**Comment by athre0z** [comment]
Hey Alexandr!

Rolling your own column oriented DB.. I've been there as well, very fun project. For me, the problem with ClickHouse is that it's just such an excellent database that made it hard to find reasons to continue on my own DB. 😅

First of all I'm happy to hear that you are interested in contributing to the project! This client is actively maintained, meaning that I (and perhaps @quinnj as well) will be happy to review PRs and respond to issues, but I'm currently not actively working on any new features. @quinnj had planned to do some stuff, but I think he got caught up in some other work, although I might be wrong and it'd probably be best to wait for a reply from him before starting anything major.

If you're looking for some guidance on what works and what is missing, I'd like to refer you to this post:
https://github.com/JuliaDatabases/ClickHouse.jl/issues/4#issuecomment-622973235

Just let me know if anything needs more clarification or you'd like some help with anything (e.g. CH protocol related things -- although, from the looks of your client, I'd guess you figured out most of the protocol yourself already).

**Comment by waralex** [comment]
>Rolling your own column oriented DB.. I've been there as well, very fun project. For me, the problem with ClickHouse is that it's just such an excellent database that made it hard to find reasons to continue on my own DB.

**Comment by waralex** [comment]
>Rolling your own column oriented DB.. I've been there as well, very fun project. For me, the problem with ClickHouse is that it's just such an excellent database that made it hard to find reasons to continue on my own DB.

I understand perfectly. The moment I let my superiors convince me to become the technical Manager of all Analytics in a c++ developer company, I stopped seeing  any reasons why I shouldn't move to clickhouse :)

**Comment by waralex** [comment]
I must warn you - I'm not very good with English, so if it turns out that I write some nonsense, just tell me about it...
