### ISSUE TITLE
Date columns are mapped to the Julia DateTime type instead of Date

### ISSUE THREAD

**Issue by waralex** [JuliaDatabases/ClickHouse.jl#7]
It seems to me that this is a mistake that is easy to fix. I will do this, but there is a compatibility issue. Will current users have problems with the fact that a column of the Date type will be received as `Vector{Date}` instead of `Vector{DateTime}`? (and a similar question about insert)

**Comment by athre0z** [comment]
Hm yeah, that would indeed be an interface breaking change, but it's probably better to do it now that this project has 6 stars than later.

On a related note, the date/datetime handling is currently somewhat flawed in the sense that it completely disregards timezones at the moment. However this somewhat blocked on https://github.com/JuliaTime/TimeZones.jl/issues/182#issuecomment-518629273 unless we want to burn a ton of performance for allocs.

**Comment by athre0z** [comment]
Resolved in #10
