### ISSUE TITLE
Transport compression (LZ4, ZStd)

### ISSUE THREAD

**Issue by athre0z** [JuliaDatabases/ClickHouse.jl#8]
Transport compression is currently not implemented and would be nice to have. In the ClickHouse TCP protocol, compression occurs on a block level and requires calculation of a `CityHash128` checksum.

Steps required to implement this feature:
- [ ] Selection of libraries for compression (LZ4, ZStd)
- [ ] Find or develop a `CityHash128` library. At the time of writing, such a library doesn't appear to exist.
- [ ] Rework block de/-encoding in a way that it supports compression

Optimally, we'd make this an optional feature and not pull in the dependencies if a user doesn't want to use transport compression.

This Python client has an implementation of transport compression and might be a nice reference -- it's generally very well written and easier to read / navigate than the official C++ client's source:
https://github.com/mymarilyn/clickhouse-driver

## Status
This issue is currently not being worked on and if anyone is interesting in taking a stab at it, please comment here in order to prevent duplicate work or to ask any further questions.

**Comment by waralex** [comment]
As far as I remember there is a special problem with the fact that the clickhouse uses its fork with some ancient version of CityHash128

**Comment by athre0z** [comment]
Implemented in https://github.com/JuliaDatabases/ClickHouse.jl/pull/33
